INSERT INTO vegetables (name, description, image_url, avatar_url, colour, difficulty, depth, climate, sun_required, water_time, harvest_date, space)
VALUES
('Beets', 'Beets are a root vegetable that provide some impressive health benefits. They are also a great source of fiber, folate, vitamin C, and contain nitrates that may aid in lower blood pressure and improved athletic performance.', '../images/vegetables/Beets.png', '../images/avatars/cartoon-beet.png', '#b30059', 2, 1, '10-26', 5, 3, 49, 4),
('Cabbage', 'Cabbage is a cole crop which is high in beta-carotene, vitamin C and fiber. It is cheap, widely available year-round, and may also reduce the risk of some forms of cancer.', '../images/vegetables/cabbage.png', '../images/avatars/cartoon-cabbage.png', '#c5ffad', 1, 1, '13-24', 4, 3, 98, 12),
('Celery', 'Celery is a marshland plant rich in vitamins and minerals with a low glycemic index. You will enjoy vitamins A, K, and C, plus minerals like potassium and folate when you eat celery.', '../images/vegetables/celery.png', '../images/avatars/cartoon-celery.png', 'lightGreen', 3, 0.5, '15-21', 6, 3, 84, 6),
('Onions', 'Onions are root vegetables that contain antioxidants and compounds that fight inflammation, decrease triglycerides and reduce cholesterol levels. They will also be the unappreciated star of every meal.', '../images/vegetables/onions.png', '../images/avatars/cartoon-onion.png', '#ffc65d', 2, 1, '20-25', 5, 7, 98, 6),
('Potatoes', 'Potatoes are a root vegetable that are rich in vitamins, minerals and antioxidants. They have been linked to a variety of impressive health benefits, including reduced heart disease risk and higher immunity.', '../images/vegetables/potatoes.png', '../images/avatars/cartoon-potato.png', '#a5741a', 1, 15, '15-20', 5, 3, 49, 35),
('Peppers', 'Peppers come in different colors, most commonly green, yellow, and red. They are an excellent source of vitamin A, vitamin C, and potassium. Bell Peppers also contain a healthy dose of fiber, folate, and iron.', '../images/vegetables/peppers.png', '../images/avatars/cartoon-pepper.png', '#f50000', 2, 0.5, '16-28', 4, 3, 63, 24),
('Tomatoes', 'Tomatoes are the major dietary source of the antioxidant lycopene, which has been linked to reduced risk of heart disease and cancer. They are also a great source of vitamin C, potassium, folate, and vitamin K.', '../images/vegetables/tomatoes.png', '../images/avatars/cartoon-tomato.png', '#f50000', 2, 0.3, '14-16', 8, 10, 49, 18),
('Cauliflower', 'Cauliflower is high in fiber and B-vitamins. It provides antioxidants and phytonutrients that can protect against cancer. It also contains choline that is essential for learning and memory, and many other important nutrients.', '../images/vegetables/cauliflower.png', '../images/avatars/cartoon-cauliflower.png', '#fcffcf', 3, 0.5, '15-18', 6, 3, 70, 24),
('Basil', 'Basil is a herb with an excellent source of vitamin K, manganese, iron, vitamin A, and vitamin C. Its also a good source of calcium, magnesium, omega-3 fatty acids, and will kick your meals up a notch.', '../images/vegetables/basil.png', '../images/avatars/cartoon-basil.png', 'green', 1, 1, '18-30', 7, 7, 49, 12),
('Summer Squash', 'Squash come in both summer and winter varieties, both containing a large number of nutrients. Squash is rich in manganese which helps to boost bone strength and helps the body’s ability to process fats and carbohydrates.', '../images/vegetables/squashes.png', '../images/avatars/cartoon-squash.png', 'yellow', 1, 2, '15-28', 7, 3, 63, 48),
('Carrots', 'Carrots are root vegetables that are crunchy, tasty, and highly nutritious. They are a particularly good source of fiber, vitamin K1, potassium, antioxidants, and have even been linked to improved eye health.', '../images/vegetables/carrots.png', '../images/avatars/cartoon-carrots.png', 'orange', 2, 5, '10-28', 7, 1, 70, 2),
('Radishes', 'Radishes are fast growing root vegetables rich in antioxidants and minerals like calcium, potassium and nitrates which help lower high blood pressure and reduce the risk for heart disease and improve blood flow.', '../images/vegetables/radish.png', '../images/avatars/cartoon-radish.png', '#ff0d86', 3, 0.5, '18-30', 3, 3, 28, 2),
('Strawberry', 'Strawberries are packed with vitamin C, fiber, antioxidants, and more. These potent little packages protect your heart, increase good cholesterol, lower your blood pressure, and guard against cancer.', '../images/vegetables/strawberry.png', '../images/avatars/cartoon-strawberry.png', '#ce001b', 1, 0.3, '20-29', 6, 1, 28, 2),
('Cucumber', 'Cucumbers are an easy-care vegetable that are delicious on their own, or as pickles! Eating cucumbers may lead to many potential health benefits, including weight loss, balanced hydration, digestive regularity and lower blood sugar levels.', '../images/vegetables/cucumbers.png', '../images/avatars/cartoon-cucumber.png', '#125c00', 2, 2, '15-30', 6, 7, 56, 30),
('Green Bean', 'Green Beans are a garden staple high in vitamin K, and they also contain a decent amount of calcium. These nutrients are important for maintaining strong, healthy bones and reducing your risk of fractures.', '../images/vegetables/grn-beans.png', '../images/avatars/cartoon-bean.png', '#5daf00', 2, 4, '18-29', 2, 7, 56, 3);
